server:
  port: 8080

spring:
  application:
    name: PRODUCT-SERVICE
  config:
    import: configserver:http://localhost:9296
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/product_db
    username: root
    password: ROOTroot
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

management:
  tracing:
    sampling:
      probability: 1.0

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}