
server:
  port: 8082

spring:
  application:
    name: PAYMENT-SERVICE
  config:
    import: configserver:http://localhost:9296
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/payment_db
    username: root
    password: ROOTroot
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

management:
  tracing:
    sampling:
      probability: 1.0